### ISSUE TITLE
1a_spacer.brd and 2a_Electodes.brd is not same as mentioned in paper.

### ISSUE THREAD

**Issue by AbidHussain70** [bhclowers/OS-IMS#1]

**Comment by bhclowers** [comment]
Hopefully, this will address the issue: https://github.com/bhclowers/OS-IMS/tree/master/PCB_IMS/Revision_Dec2020

**Comment by AbidHussain70** [comment]
Board dimensions are not set. 
This detector board Gerber file output in jlcbcb.
![image](https://user-images.githubusercontent.com/23444211/101711033-aa9c2a80-3acd-11eb-8825-fd10f8ded9c9.png)

IMS_Electrode_1in_R4.brd is different, not same as paper and also no dimension. For this I can set dimension from the paper. 

![image](https://user-images.githubusercontent.com/23444211/101711177-05358680-3ace-11eb-95e3-e5acf75dcea1.png)



**Spacers1_25_Single.brd has no dimension.**

**Comment by bhclowers** [comment]
It looks like you might not have the appropriate layers set on your cam export settings for Eagle.  You need to make sure you are exporting your mill and dimension layers appropriately.  In the future, please create a separate issue to keep things organized. 

Sparkfun and Adafruit have some decent tutorials on how to set this.  Also, Eagle has a layer preview setting that can be useful.

https://learn.sparkfun.com/tutorials/designing-pcbs-advanced-smd/gerber-generation

Your board should look something like this: 
<img width="587" alt="Detector" src="https://user-images.githubusercontent.com/385793/101715744-d75e2c80-3a50-11eb-99c8-ae63435b2027.png">

Good luck!
