### ISSUE TITLE
The aperture grid is etched stainless steel grid? And how to connect? 

### ISSUE THREAD

**Issue by AbidHussain70** [bhclowers/OS-IMS#10]
In the paper you mentioned that drift tube is terminated with aperture grid, 
following lines are from your paper.

__To shield the detector from an image current induced from the approaching ion cloud, the drift tube is terminated with an aperture grid which is directly placed on the last electrode, followed by 1 spacer and finally the detector. The aperture grid is connected via a 500 k resistor to ground, as shown in Fig. 12. To stabilize the voltage on the aperture grid, it is advantageous to add an additional capacitor (we used 0.22mF) in parallel to the resistor._

I have few questions;

1) What is aperture grid? it is etched stainless steel grid?
2) How to connect Detector to drift tube? Can you please explain this figure?
its from your paper.

![image](https://user-images.githubusercontent.com/23444211/112247280-fe064300-8c8e-11eb-90c5-fe2069514728.png)

3) Where should I connect the ground terminal of the supply (common ground)?

**Comment by AbidHussain70** [comment]
Hi, 
can you explain?

**Comment by bhclowers** [comment]
You need to ground your supply as specified by the manufactuer.  I would ground that grid to the same ground as your amplifier.  The grid is a wire set or the etched grid as specified in the paper.  The electronic diagram as depicted is correct. I'm not sure how else describe it other than through a schematic.

**Comment by AbidHussain70** [comment]
Thanks for explanation.
Electronic schematic is correct but the missing part is the common ground (for negative terminal) for all the setup. Schematic is just for shutter grid part it does not say any thing about the whole circuit (setup). In the setup we have to use 4 power sources, one for Amplifier, one for Pulser, one HV source for ESI and one HV for electrodes. I could not find any explanation for ground terminal (negative terminal). 

From your explanation I will connect shutter grid' ground (negative terminal) with amplifier' ground (negative terminal).
