### ISSUE TITLE
Amplifier PCB circuit is not labelled.

### ISSUE THREAD

**Issue by AbidHussain70** [bhclowers/OS-IMS#2]
I2V_Rev4.brd file provided in your repository has no labelling for the components. 

![image](https://user-images.githubusercontent.com/23444211/102753827-f476f180-43a6-11eb-9e30-918a6b494170.png)

**Comment by bhclowers** [comment]
For some reason these were removed.  Feel free to add them back in.  Unfortuantely, I don't have the bandwidth right now to make this happen. The good news is that the parts have not really changed in any way from the older gerber files released.

**Comment by Bendermat** [comment]
Hello @bhclowers, I am trying to build this IMS prototype and I have a question:
do you happen to have the released gerber files for the amplifier mentioned in your paper?
They were named as "9_amplifier_gerbers.zip" but I cannot find them in the folder here.
Thank you in advance.
