### ISSUE TITLE
IMS_Electrode_1in_R4.brd board has one electrode on each.

### ISSUE THREAD

**Issue by AbidHussain70** [bhclowers/OS-IMS#4]
IMS_Electrode_1in_R4.brd has one electrode on each side while in the paper both electrodes are on one side of the PCB circuit.
My Question is Does it will effect the assembly or not? If not I will use this circuit board. 

![image](https://user-images.githubusercontent.com/23444211/102755670-baf3b580-43a9-11eb-8ffe-892105e78b95.png)

**Comment by bhclowers** [comment]
In the paper we were aiming to use the DC Coupler to hold the electrodes with solder on the top and the bottom with electrodes on both sides.  However, we noticed that doing so requried additional insulating considerations as the high voltage would now be on both sides of the board.  Moreover, the compression rods do a pretty decent job of holding things together.  For these reasons, we nixed the second electrode. Hope that clears it up.
