### ISSUE TITLE
corona needle should be connected to the SMA connector?

### ISSUE THREAD

**Issue by AbidHussain70** [bhclowers/OS-IMS#6]
In the paper, in section 6, corona needle placement is described briefly. I paste that portion of paper below: 

 _**For the measurement of the corona-ionizationspectrum (Fig. 17(a)), a home built corona needle was placed centric and in close proximity to the first ring of the desolvationregion and connected to an electric potential of 14.5 kV. Then, sampled headspace from 2,4-lutidine was applied via a PEEK capillary which is connected to a gas tight syringe containing the sample. The capillary sample inlet is shown inFig. 16. Theassembly is similar to the assembly of the drift gas inlet described above, while using a 0.01 ID/0.062 OD PEEK capillaryinstead of the Teflon hose. Due to the smaller diameter of the capillary compared to the Teflon hose, only one (middle) ofthe three spacers used has a cut out. It should be noted that a range of gas-phase sample introduction mechanisms maybe implemented 

(PDF) Implementation of a Flexible, Open-Source Platform for Ion Mobility Spectrometry. Available from: https://www.researchgate.net/publication/325255050_Implementation_of_a_Flexible_Open-Source_Platform_for_Ion_Mobility_Spectrometry [accessed Mar 08 2021].**_

### My Question is,
Should I attach the corona needle into SMA connector or should I palace it at a distance?

**Comment by bhclowers** [comment]
I'm not sure about your connection.  SMA is a signal connector and not a HV connector.  The tip of the corona needle should be placed a couple of mm inside the desolvation/reaction region. 

Something like this:

IMS Rings_____________ |   |   |   |   |   |

Corona Needle ------->                             

IMS Rings_____________ |   |   |   |   |   |

Ignore the underines in the text digram.  This is just for spacing.

**Comment by AbidHussain70** [comment]
This is how I made the final assembly. For the needle I add a support to make it fixed.
![Assemble](https://user-images.githubusercontent.com/23444211/114504546-9aee4780-9c61-11eb-88d7-dfbacd88e476.jpg)
