### ISSUE TITLE
Corona needle requires separate power source?

### ISSUE THREAD

**Issue by AbidHussain70** [bhclowers/OS-IMS#7]
The first ring of the desolvation region should be connected to an electric potential of 11.5 kV via a high voltage power supply. and corona needle needs a power supply with almost same potential. 

Can I use same power supply or should I use separate power source?

**Comment by bhclowers** [comment]
Yes, the corona supply will require a separate supply.  If you have access to a floating supply, you can float the corona on top of the drift voltage.  However, care should be taken to ramp the corona and drift voltages up simultaneously.  It is important to make sure the voltage differential between the corona and the IMS drift potential isn't too large as to cause a catastrophic arc.
