### ISSUE TITLE
Can I use Teflon Hose for gaseous inlet?

### ISSUE THREAD

**Issue by AbidHussain70** [bhclowers/OS-IMS#8]
Can I use the same Teflon hose--used in draft gas inlet, for gaseous inlet or should I use 01 ID/0.062 OD PEEK capillary mention in the paper?

**Comment by bhclowers** [comment]
If you are referring talking about the drift gas inlet, 0.062 inlet might be a little small for 300 mL/min.  However, it should work.  As for a sample inlet, the volume of this tube should be ok. However, the smaller ID for the sample inlet, the fast the sample will arrive into the reaction region.

**Comment by AbidHussain70** [comment]
I used 1.6mm inner diameter Teflon hose for Drift gas inlet and I ordered 0.25 mm PEEK capillary for sample injection. 
Thanks
