### ISSUE TITLE
Final Assembly!

### ISSUE THREAD

**Issue by AbidHussain70** [bhclowers/OS-IMS#9]
I finished the assembly of OS-IMS,

![IMS-complete](https://user-images.githubusercontent.com/23444211/112102787-be365180-8be3-11eb-91c7-23bd68e5cdb7.jpg)

This is my final assembly, I have few questions before I start testing the device.

**1) I used a conductor needle (200 micron) for sample injection, is it fine or should I used non-conductor material like PEEK capillary, the one you used in your paper?
2) I put three shatter grid between drift and desolvation region. And the last electrode of both drift and desolvation region is connected to the first and third grid respectively. I put insulator between first and second grid and second and third grid. Is this configuration correct or should I make some changes?
3) Should I use floating power source, by floating I mean should I use just positive terminal of the HV power source?
If I need to connect the negative terminal of the HV source, which point should I attach the negative terminal?**

**Comment by AbidHussain70** [comment]
![image](https://user-images.githubusercontent.com/23444211/112273551-6cabc680-8cb8-11eb-83c2-c1a7b2687d58.png)

For grid shatter what I understood is, first and last grids are in direct contact with electrodes. And I put spacers between 2nd and 3rd. 
I read all the links but I need to know above points (which I mentioned in the issue). Can you please guide me?

**Comment by bhclowers** [comment]
The sample injector looks like it is metal. If that is the HV end, you need to address that issue.  A metal needle located at the HV end cannot be floated.  It will arc.  Additionally, you need to make sure there are insulating spacers (i.e. teflon or kapton) between the grids.  The grids should not be touching each other in any fashion when assembled.

**Comment by AbidHussain70** [comment]
I changed the sample injector to a capillary tube (200um).  And I will put a common ground (big aluminum plate), for attaching all the ground terminals. 

![Assemble](https://user-images.githubusercontent.com/23444211/114335958-7ff7d680-9b80-11eb-9245-f64899164473.jpg)
